# Generated by Django 5.2.1 on 2025-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(default='undefined', max_length=100),
        ),
    ]
