# Generated by Django 5.2.1 on 2025-05-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_App', '0002_ordereditem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(default=0.0),
        ),
    ]
